security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        main:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        main:
            provider: main
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: adminDashboard
                always_use_default_target_path: true
            logout:
                path: logout
                target: home

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
